# Generated by Django 5.1.5 on 2026-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('회원_index', models.AutoField(primary_key=True, serialize=False)),
                ('회원id', models.CharField(max_length=50, unique=True)),
                ('회원비밀번호', models.CharField(max_length=255)),
                ('이름', models.CharField(max_length=50)),
                ('연락처', models.CharField(max_length=20)),
                ('아파트동', models.IntegerField()),
                ('아파트호수', models.IntegerField()),
                ('아파트평수', models.IntegerField()),
                ('가구원수', models.IntegerField()),
            ],
            options={
                'db_table': '회원정보',
            },
        ),
    ]
