# Generated by Django 5.1.5 on 2026-09-07 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementFee',
            fields=[
                ('관리비_index', models.AutoField(primary_key=True, serialize=False)),
                ('청구년월', models.CharField(max_length=8)),
                ('납부상태', models.BooleanField(default=True)),
                ('합계금액', models.IntegerField()),
                ('전기세', models.IntegerField()),
                ('수도세', models.IntegerField()),
                ('가스비', models.IntegerField()),
                ('일반관리비', models.IntegerField()),
                ('공동전기료', models.IntegerField()),
                ('청소비', models.IntegerField()),
                ('경비비', models.IntegerField()),
                ('승강기전기료', models.IntegerField()),
                ('수선유지비', models.IntegerField()),
                ('회원', models.ForeignKey(db_column='회원_index', on_delete=django.db.models.deletion.CASCADE, related_name='관리비목록', to='accounts.member')),
            ],
            options={
                'db_table': '관리비',
                'indexes': [models.Index(fields=['청구년월'], name='관리비_청구년월_3332d1_idx')],
                'unique_together': {('회원', '청구년월')},
            },
        ),
    ]
